version: '3.9'
################################################################################
x-timezone: &timezone TZ=Canada/Eastern

x-deploy_policy: &deploy
  replicas: 1
  restart_policy:
    condition: any
    delay: 5s
    max_attempts: 3
    window: 5s
  update_config:
    order: stop-first
    delay: 10s
    failure_action: rollback
    max_failure_ratio: 0.25
  rollback_config:
    order: stop-first
    failure_action: continue

################################################################################
services:
  auth:
    image: 10.222.5.70:5000/aga-single-entry-point-back:4.0 # Remplacer par la bonne image
    networks:
      - int_network_portailaga
    environment:
      - *timezone
      - NODE_ENV=production
      - PORT=8080

    deploy:
      <<: *deploy
    secrets:
      - JDBENEFITS_API_KEY
      - ADHERENTS_API_KEY
      - ADHESION_API_KEY
      - WBLLIBERT_API_KEY
      - PPIBMW_API_KEY
      - OLIVERAPP_API_KEY

  client:
    image: 10.222.5.70:5000/aga-single-entry-point-front:latest # Remplacer par la bonne image
    networks:
      - int_network_portailaga
    environment:
      - *timezone
    deploy:
      <<: *deploy

  nginx:
    image: nginx:latest
    networks:
      - int_network_portailaga
    ports:
      - 8081:80 # Port 8081 du serveur local vers le port 80 de Nginx
    environment:
      - *timezone
    volumes:
      - /srv/docker/services/aga-portail/nginx:/etc/nginx/conf.d/ # Chemin vers votre fichier de configuration Nginx
    deploy:
      <<: *deploy

secrets:
  JDBENEFITS_API_KEY:
    external: true
  ADHERENTS_API_KEY:
    external: true
  ADHESION_API_KEY:
    external: true
  WBLLIBERT_API_KEY:
    external: true
  PPIBMW_API_KEY:
    external: true
  OLIVERAPP_API_KEY:
    external: true

networks:
  int_network_portailaga:
    name: int_network_portailaga
    attachable: false
    driver: overlay
    internal: false
